#ifndef FLUIDICMACHINEMODEL_GLOBAL_H
#define FLUIDICMACHINEMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FLUIDICMACHINEMODEL_LIBRARY)
#  define FLUIDICMACHINEMODELSHARED_EXPORT Q_DECL_EXPORT
#  define MACHINE_FLOW_EXPORT Q_DECL_EXPORT
#  define MACHINEGRAPH_EXPORT Q_DECL_EXPORT
#  define MACHINEGRAPHGENERATOR_EXPORT Q_DECL_EXPORT
#  define GRAPHRULESGENERATOR_EXPORT Q_DECL_EXPORT
#  define VARIABLE_NOMINATOR_EXPORT Q_DECL_EXPORT
#  define LABELCOMBINATIONITERATOR_EXPORT Q_DECL_EXPORT
#  define MACHINEGRAPHITERATOR_EXPORT Q_DECL_EXPORT
#  define MACHINESTATE_EXPORT Q_DECL_EXPORT
#  define CONTAINERNODE_EXPORT Q_DECL_EXPORT
#  define VARIABLE_EXPORT Q_DECL_EXPORT
#  define INTEGERNUMBER_EXPORT Q_DECL_EXPORT
#  define VARIABLEDOMAIN_EXPORT Q_DECL_EXPORT
#  define EQUALITY_EXPORT Q_DECL_EXPORT
#  define CONJUCTION_EXPORT Q_DECL_EXPORT
#  define BINARYOPERATION_EXPORT Q_DECL_EXPORT
#  define FLUIDICMODEL_UNARYOPERATION_EXPORT Q_DECL_EXPORT
#  define PUMPNODE_EXPORT Q_DECL_EXPORT
#  define VALVENODE_EXPORT Q_DECL_EXPORT
#  define FLUIDICMACHINENODE_EXPORT Q_DECL_EXPORT
#else
#  define FLUIDICMACHINEMODELSHARED_EXPORT Q_DECL_IMPORT
#  define MACHINE_FLOW_EXPORT Q_DECL_IMPORT
#  define MACHINEGRAPH_EXPORT Q_DECL_IMPORT
#  define MACHINEGRAPHGENERATOR_EXPORT Q_DECL_IMPORT
#  define GRAPHRULESGENERATOR_EXPORT Q_DECL_IMPORT
#  define VARIABLE_NOMINATOR_EXPORT Q_DECL_IMPORT
#  define LABELCOMBINATIONITERATOR_EXPORT Q_DECL_IMPORT
#  define MACHINEGRAPHITERATOR_EXPORT Q_DECL_IMPORT
#  define MACHINESTATE_EXPORT Q_DECL_IMPORT
#  define CONTAINERNODE_EXPORT Q_DECL_IMPORT
#  define VARIABLE_EXPORT Q_DECL_IMPORT
#  define INTEGERNUMBER_EXPORT Q_DECL_IMPORT
#  define VARIABLEDOMAIN_EXPORT Q_DECL_IMPORT
#  define EQUALITY_EXPORT Q_DECL_IMPORT
#  define CONJUCTION_EXPORT Q_DECL_IMPORT
#  define BINARYOPERATION_EXPORT Q_DECL_IMPORT
#  define FLUIDICMODEL_UNARYOPERATION_EXPORT Q_DECL_IMPORT
#  define PUMPNODE_EXPORT Q_DECL_IMPORT
#  define VALVENODE_EXPORT Q_DECL_IMPORT
#  define FLUIDICMACHINENODE_EXPORT Q_DECL_IMPORT
#endif

#endif // FLUIDICMACHINEMODEL_GLOBAL_H
