#ifndef FLUIDICMACHINEMODEL_GLOBAL_H
#define FLUIDICMACHINEMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FLUIDICMACHINEMODEL_LIBRARY)
#  define FLUIDICMACHINEMODELSHARED_EXPORT Q_DECL_EXPORT
#  define VARIABLE_EXPORT Q_DECL_EXPORT
#  define BINARYOPERATION_EXPORT Q_DECL_EXPORT
#  define IMPLICATION_EXPORT Q_DECL_EXPORT
#  define EQUALITY_EXPORT Q_DECL_EXPORT
#  define CONJUCTION_EXPORT Q_DECL_EXPORT
#  define INTEGERNUMBER_EXPORT Q_DECL_EXPORT
#else
#  define FLUIDICMACHINEMODELSHARED_EXPORT Q_DECL_IMPORT
#  define VARIABLE_EXPORT Q_DECL_IMPORT
#  define BINARYOPERATION_EXPORT Q_DECL_IMPORT
#  define IMPLICATION_EXPORT Q_DECL_IMPORT
#  define EQUALITY_EXPORT Q_DECL_IMPORT
#  define CONJUCTION_EXPORT Q_DECL_IMPORT
#  define INTEGERNUMBER_EXPORT Q_DECL_IMPORT
#endif

#endif // FLUIDICMACHINEMODEL_GLOBAL_H
