#ifndef FLUIDICMACHINEMODEL_GLOBAL_H
#define FLUIDICMACHINEMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FLUIDICMACHINEMODEL_LIBRARY)
#  define FLUIDICMACHINEMODELSHARED_EXPORT Q_DECL_EXPORT
#  define VARIABLE_EXPORT Q_DECL_EXPORT
#  define BINARYOPERATION_EXPORT Q_DECL_EXPORT
#  define VARIABLEDOMAIN_EXPORT Q_DECL_EXPORT
#  define EQUALITY_EXPORT Q_DECL_EXPORT
#  define CONJUCTION_EXPORT Q_DECL_EXPORT
#  define INTEGERNUMBER_EXPORT Q_DECL_EXPORT
#  define MACHINE_FLOW_EXPORT Q_DECL_EXPORT
#  define SEQUENCE_EXPORT Q_DECL_EXPORT
#  define MACHINEGRAPH_EXPORT Q_DECL_EXPORT
#  define PLUGINCONFIGURATION_EXPORT Q_DECL_EXPORT
#  define PUMPPLUGINFUNCTION_EXPORT Q_DECL_EXPORT
#  define VALVEPLUGINGROUTINGFUNCTION_EXPORT Q_DECL_EXPORT
#  define UNARYOPERATION_EXPORT Q_DECL_EXPORT
#  define MACHINEGRAPHGENERATOR_EXPORT Q_DECL_EXPORT
#  define SEQUENCE_EXPORT Q_DECL_EXPORT
#  define GRAPHRULESGENERATOR_EXPORT Q_DECL_EXPORT
#  define VARIABLE_NOMINATOR_EXPORT Q_DECL_EXPORT
#  define LABELCOMBINATIONITERATOR_EXPORT Q_DECL_EXPORT
#  define UTILS_EXPORT Q_DECL_EXPORT
#  define MACHINEGRAPHITERATOR_EXPORT Q_DECL_EXPORT
#else
#  define FLUIDICMACHINEMODELSHARED_EXPORT Q_DECL_IMPORT
#  define VARIABLE_EXPORT Q_DECL_IMPORT
#  define BINARYOPERATION_EXPORT Q_DECL_IMPORT
#  define VARIABLEDOMAIN_EXPORT Q_DECL_IMPORT
#  define EQUALITY_EXPORT Q_DECL_IMPORT
#  define CONJUCTION_EXPORT Q_DECL_IMPORT
#  define INTEGERNUMBER_EXPORT Q_DECL_IMPORT
#  define MACHINE_FLOW_EXPORT Q_DECL_IMPORT
#  define SEQUENCE_EXPORT Q_DECL_IMPORT
#  define MACHINEGRAPH_EXPORT Q_DECL_IMPORT
#  define PLUGINCONFIGURATION_EXPORT Q_DECL_IMPORT
#  define PUMPPLUGINFUNCTION_EXPORT Q_DECL_IMPORT
#  define VALVEPLUGINGROUTINGFUNCTION_EXPORT Q_DECL_IMPORT
#  define UNARYOPERATION_EXPORT Q_DECL_IMPORT
#  define MACHINEGRAPHGENERATOR_EXPORT Q_DECL_IMPORT
#  define SEQUENCE_EXPORT Q_DECL_IMPORT
#  define GRAPHRULESGENERATOR_EXPORT Q_DECL_IMPORT
#  define VARIABLE_NOMINATOR_EXPORT Q_DECL_IMPORT
#  define LABELCOMBINATIONITERATOR_EXPORT Q_DECL_IMPORT
#  define UTILS_EXPORT Q_DECL_IMPORT
#  define MACHINEGRAPHITERATOR_EXPORT Q_DECL_IMPORT
#endif

#endif // FLUIDICMACHINEMODEL_GLOBAL_H
