#ifndef FLUIDICMACHINEMODEL_GLOBAL_H
#define FLUIDICMACHINEMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FLUIDICMACHINEMODEL_LIBRARY)
#  define FLUIDICMACHINEMODELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FLUIDICMACHINEMODELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FLUIDICMACHINEMODEL_GLOBAL_H
